import org.springframework.jdbc.core.BeanPropertyRowMapper
import org.springframework.jdbc.core.JdbcTemplate

class LivroRepositorio {

        lateinit var jdbcTemplate: JdbcTemplate

        fun iniciar(conexao: JdbcTemplate) {
            jdbcTemplate = conexao
        }

    fun criarTabelas(){
        jdbcTemplate!!.execute("""
            create table livro(
            id INT GENERATED BY DEFAULT AS IDENTITY primary key,
            titulo varchar(45),
            autor varchar(45),
            dataCriacao DATE
            )
        """.trimIndent())
    }

    fun cadastrar(novoLivro: Livro){
        jdbcTemplate.execute("""
            INSERT INTO livro(titulo, autor, dataCriacao) VALUES ( '${novoLivro.titulo}', '${novoLivro.autor}', '${novoLivro.dataCriacao}')
        """.trimIndent())
    }

    fun consultar(id: Int):Livro{
        val livro = jdbcTemplate.queryForObject("""
            SELECT * FROM livro WHERE id = $id
        """, BeanPropertyRowMapper(Livro::class.java))
        return livro
    }
}