import org.apache.commons.dbcp2.BasicDataSource
import org.springframework.jdbc.core.BeanPropertyRowMapper
import org.springframework.jdbc.core.JdbcTemplate
import javax.swing.JOptionPane

fun main() {
    val dataSource = BasicDataSource();
    dataSource.driverClassName = "org.h2.Driver";
    dataSource.url ="jdbc:h2:mem:sptech"
    dataSource.username = "sa"
    dataSource.password = ""
    val jdbcTemplate = JdbcTemplate(dataSource)

    jdbcTemplate.execute("""
        CREATE TABLE musica(
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            interprete varchar(20) NOT NULL,
            acessosSpotify INT,
            acessoEncerrado TINYINT
        )
    """)

    var contador = 1
    while(contador < 3){
        val musica1 = Musica()

        musica1.interprete = JOptionPane.showInputDialog("Qual o interprete?")

        musica1.acessosSpotify = JOptionPane.showInputDialog("Quantos acessos no spotify?").toInt()

        JOptionPane.showMessageDialog(null, "A música cantada por ${musica1.interprete} teve ${musica1.acessosSpotify} acessos")

        var encerrado = JOptionPane.showInputDialog("O acesso ao spotify foi encerrado? Digite 1 para sim ou qualque outra coisa para não")

        if(encerrado == "1"){
            musica1.acessoEncerrado = true
        }

        jdbcTemplate.update("""
        insert into musica(interprete, acessosSpotify, acessoEncerrado) values
        ('${musica1.interprete}', ${musica1.acessosSpotify}, ${musica1.acessoEncerrado})
    """)
        contador ++
    }

    val listaMusicas:List<Musica> = jdbcTemplate.query(
        "select * from musica",
        BeanPropertyRowMapper(Musica::class.java)
    )
    listaMusicas.forEach{

        if(it.acessoEncerrado){
            JOptionPane.showMessageDialog(null, "A música cantada por ${it.interprete} teve ${it.acessosSpotify} acessos e seu acesso já foi encerrado")
        } else {
            JOptionPane.showMessageDialog(null, "A música cantada por ${it.interprete} teve ${it.acessosSpotify} acessos")
        }
    }

    jdbcTemplate.update("TRUNCATE TABLE musica")

}