import org.springframework.jdbc.core.BeanPropertyRowMapper
import org.springframework.jdbc.core.JdbcTemplate

class MusicaRepositorio {
    lateinit var jdbcTemplate: JdbcTemplate

    fun iniciar(conexao: JdbcTemplate) {
        jdbcTemplate = conexao
    }

    fun criarTabelas(){
        jdbcTemplate!!.execute("""
            create table musica(
            id INT GENERATED BY DEFAULT AS IDENTITY primary key,
            titulo varchar(45),
            artista varchar(45),
            dataCriacao DATE
            )
        """.trimIndent())
    }

    fun cadastrar(novaMusica: Musica){
        jdbcTemplate.execute("""
            INSERT INTO musica(titulo, artista, dataCriacao) VALUES ( '${novaMusica.titulo}', '${novaMusica.artista}', '${novaMusica.dataCriacao}')
        """.trimIndent())
    }

    fun consultar(id: Int):Musica{
        val musica = jdbcTemplate.queryForObject("""
            SELECT * FROM musica WHERE id = $id
        """, BeanPropertyRowMapper(Musica::class.java)
        )
        return musica
    }

    fun deletar(id: Int): Boolean{
        val deletado = jdbcTemplate.update(
            """
                DELETE FROM musica WHERE id = ${id}
            """.trimIndent())
        return deletado>0
    }
}